[package]
name = "validator_tvl_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
serde = "1.0.202"
serde_json = "1.0.117"
shellexpand = "3.1.0"
solana-account-decoder = "1.18.14"
solana-client = "1.18.14"
solana-sdk = "1.18.14"
